//
// Created by henri on 28.09.23.
//

#ifndef CONVEXADJUSTALBEROBUSTOPTIMIZATION_SOLVER_H
#define CONVEXADJUSTALBEROBUSTOPTIMIZATION_SOLVER_H


class Solver {

};


#endif //CONVEXADJUSTALBEROBUSTOPTIMIZATION_SOLVER_H
