//
// Created by henri on 18.06.24.
//

#ifndef CONVEXADJUSTALBEROBUSTOPTIMIZATION_SOLVER_H
#define CONVEXADJUSTALBEROBUSTOPTIMIZATION_SOLVER_H


class Solver {

};


#endif //CONVEXADJUSTALBEROBUSTOPTIMIZATION_SOLVER_H
